version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      - image: cimg/python:3.9
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: trussworks/gh-cli:dc6e025d5ce37fd8656f839108b3dae0531c5b3d
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >>
      - run:
          name: Move checksum to workspace
          command: |
            mkdir -p workspace
            cp checksums.txt workspace/checksums.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - checksums.txt
  validate:
    docker:
      - image: trussworks/circleci:efb1042e31538677779971798e0912390f699e72
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME

    steps:
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: Run pre-commit tests
          command: pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: ./sleuth/requirements.txt
          pkg-manager: pip
          include-python-in-cache-key: true
      - run:
          command: |
            pytest
  terratest:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:efb1042e31538677779971798e0912390f699e72
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        - go-mod-sources-v1-{{ checksum "go.sum" }}
    - attach_workspace:
        at: /tmp/workspace
    - run:
        command: |
          temp_role=$(aws sts assume-role --role-arn arn:aws:iam::313564602749:role/circleci --role-session-name circleci)
          export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
          export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
          export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
          export RELEASE_TAG=<< pipeline.git.tag >>
          export VALIDATION_SHA=$(cut -f1 -d' ' /tmp/workspace/checksums.txt)
          make test
        name: Assume role, run pre-commit and run terratest
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}
        paths:
        - ~/go/pkg/mod

workflows:
  version: 2
  validate:
    jobs:
      - validate:
          context:
          - org-global
      - python-test:
          context:
          - org-global

  release:
    jobs:
      - release:
          context:
          - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/
      - terratest:
          context:
          - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/
          requires:
            - release
