version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.11
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
  release:
    docker:
      - image: trussworks/gh-cli:dc6e025d5ce37fd8656f839108b3dae0531c5b3d
        auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
    steps:
      - checkout
      - run:
          name: Build
          command: scripts/build
      - run:
          name: Release
          command: scripts/release $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME << pipeline.git.tag >>
      - run:
          name: Move checksum to workspace
          command: |
            mkdir -p workspace
            cp checksums.txt workspace/checksums.txt
      - persist_to_workspace:
          root: workspace
          paths:
            - checksums.txt
  python-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: ./sleuth/requirements.txt
          pkg-manager: pip
          include-python-in-cache-key: true
      - run:
          command: |
            pytest
workflows:
  version: 2

  release:
    jobs:
      - release:
          context:
            - org-global
          filters:
            branches:
              ignore: /^.*/
            tags:
              only: /^v.*/
