#!/bin/bash

PUBLIC_BUCKET="trussworks-tools-us-west-2"
GITHUB_USER="trussworks"
GITHUB_REPO="terraform-aws-iam-sleuth"
ZIP_NAME="deployment.zip"
NEW_TAG="1.0.7"

docker pull cibuilds/github
docker run --env GITHUB_TOKEN="$GITHUB_TOKEN" --rm -v "$(pwd)":/usr/local/src/your-app cibuilds/github ghr -u $GITHUB_USER -r $GITHUB_REPO $NEW_TAG /usr/local/src/your-app/$ZIP_NAME

if [[ -n "${CIRCLECI+x}" ]]; then
    // assume roles
    temp_role=$(aws sts assume-role \
                      --role-arn arn:aws:iam::313564602749:role/circleci \
                      --role-session-name circleci )
              export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
              export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
              export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
    aws s3 cp $ZIP_NAME s3://$PUBLIC_BUCKET/iam-sleuth/$NEW_TAG/$ZIP_NAME --sse AES256
else
    AWS_VAULT_KEYCHAIN_NAME=login aws-vault exec trussworks-prod -- aws s3 cp $ZIP_NAME s3://$PUBLIC_BUCKET/iam-sleuth/$NEW_TAG/$ZIP_NAME --sse AES256