name: validate-tf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-tf:
    uses: trussworks/shared-actions/.github/workflows/validate-tf.yml@ac63fe66028d60a5d5259cd2ccbe4de7e3d6b25e # v0.0.3
